# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cep',
            field=models.CharField(max_length=30, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='service',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
