# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
