# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('contract', '0002_auto_20160301_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service')),
            ],
            options={
                'ordering': ['start'],
                'verbose_name': 'Serviço Contratado',
                'verbose_name_plural': 'Serviços Contratados',
            },
        ),
    ]
