# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=150)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
                'verbose_name': 'Product',
            },
        ),
    ]
